(function (root) {
  "use strict";
  const items = [
    {
      id: "lake",
      title: "去东湖，收集一整个下午的绿",
      category: "户外自然",
      place: "东湖绿道 · 磨山段",
      price: 0,
      hours: 3,
      indoor: false,
      group: 6,
      tag: "本周精选",
      image: "photo-1441974231531-c6227db76b6e",
      desc: "沿着湖边慢慢走，让风替你清空一周的疲惫。",
      tags: ["轻徒步", "湖畔放空"],
      time: "周六 14:00 – 17:00",
      transport: "地铁 8 号线梨园站，转公共交通前往绿道",
      booking: "绿道漫步通常无需预约；具体开放情况请出发前确认。",
      route: "绿道入口集合 → 湖边漫步 → 林间休息 → 日落前返回",
      tip: "建议穿舒适运动鞋，带水、防晒和驱蚊用品。遇雷雨请取消户外行程。",
    },
    {
      id: "art",
      title: "在美术馆，和灵感待一会儿",
      category: "艺术展览",
      place: "湖北美术馆 · 武昌区",
      price: 0,
      hours: 2,
      indoor: true,
      group: 4,
      tag: "雨天也精彩",
      image: "photo-1579783902614-a3fb3927b6a5",
      desc: "不必看懂每幅画，找到让你停下来的那一幅。",
      tags: ["室内好去处", "艺术漫游"],
      time: "周日 10:00 – 12:00",
      transport: "地铁 8 号线省博湖北日报站附近",
      booking: "请前往场馆官方渠道确认开放时间并预约；此处不提供门票。",
      route: "入馆参观 → 挑选喜欢的作品 → 文创商店 → 周边午餐",
      tip: "带好身份证件。展览及免费政策以场馆公告为准。",
    },
    {
      id: "market",
      title: "昙华林散步，淘一点小美好",
      category: "城市漫游",
      place: "昙华林 · 武昌区",
      price: 45,
      hours: 3,
      indoor: false,
      group: 6,
      tag: "慢生活提案",
      image: "photo-1442512595331-e89e73853f31",
      desc: "街角咖啡、独立小店，还有不赶时间的快乐。",
      tags: ["街巷漫步", "咖啡小店"],
      time: "周六 13:30 – 16:30",
      transport: "地铁 5 号线昙华林武胜门站",
      booking: "街区漫步无需预约，店铺消费自选。",
      route: "街区入口 → 老建筑拍照 → 独立小店 → 咖啡休息",
      tip: "预算含一杯饮品与小吃的示例估算，额外购物另计。",
    },
    {
      id: "music",
      title: "把周末，交给一场现场音乐",
      category: "音乐演出",
      place: "武汉 Livehouse · 示例场次",
      price: 98,
      hours: 2,
      indoor: true,
      group: 6,
      tag: "夜晚有回响",
      image: "photo-1470229722913-7c0e2dbbafd3",
      desc: "和同频的人站在一起，让喜欢的旋律发生。",
      tags: ["室内演出", "结伴更快乐"],
      time: "周六 19:30 – 21:30",
      transport: "具体场地与交通请以实际购票信息为准",
      booking: "示例活动，无真实售票场次。请在正规票务平台查询实际演出。",
      route: "提前到场 → 核验入场 → 现场演出 → 结伴返程",
      tip: "请先核对真实演出信息、票价及入场年龄要求，再安排计划。",
    },
    {
      id: "river",
      title: "追一场江滩落日，等城市亮灯",
      category: "城市漫游",
      place: "汉口江滩 · 江岸区",
      price: 15,
      hours: 2,
      indoor: false,
      group: 6,
      tag: "日落收藏家",
      image: "photo-1473448912268-2022ce9509d8",
      desc: "带一杯饮料，和朋友分享今天最后的阳光。",
      tags: ["日落散步", "低预算"],
      time: "周日 16:30 – 18:30",
      transport: "地铁 1 号线或 6 号线大智路站，步行前往",
      booking: "公共区域漫步无需预约；以开放公告为准。",
      route: "江滩入口 → 沿江步道 → 日落拍照 → 晚餐自由安排",
      tip: "注意天气、水位及公园开放公告，不进入封闭区域。",
    },
    {
      id: "book",
      title: "躲进书店，把时间翻慢一点",
      category: "艺术展览",
      place: "武汉独立书店 · 示例路线",
      price: 35,
      hours: 2,
      indoor: true,
      group: 2,
      tag: "一个人也很好",
      image: "photo-1507842217343-583bb7270b66",
      desc: "一本意外发现的书，一杯热咖啡，刚刚好。",
      tags: ["阅读充电", "雨天备选"],
      time: "周日 14:00 – 16:00",
      transport: "选择学校附近可公共交通到达的书店",
      booking: "请出发前确认实际店铺营业时间与座位情况。",
      route: "挑一本书 → 安静阅读 → 写下喜欢的一句话",
      tip: "预算为饮品示例估算，不包含购书费用。适合独处或双人出行。",
    },
  ];
  const metadata = {
    lake: {
      source: {
        name: "武汉市政府 · 东湖绿道",
        url: "https://www.wuhan.gov.cn/sy/whyw/202406/t20240625_2420046.shtml",
        publishedAt: "2024-06-25",
      },
      time: "建议 14:00 – 17:00",
      kind: "常设目的地",
    },
    market: {
      source: {
        name: "武汉市商务局 · 昙华林攻略",
        url: "https://sw.wuhan.gov.cn/xwdt/gzdt/202405/t20240527_2407321.shtml",
        publishedAt: "2024-05-27",
      },
      time: "建议 13:30 – 16:30",
      kind: "常设目的地",
      tip: "街区自由漫步；¥45 为本产品预留的饮品小吃预算，不是门票或商家报价。",
    },
    river: {
      source: {
        name: "武汉市政府 · 江滩介绍",
        url: "https://www.wuhan.gov.cn/zwgk/xxgk/zdjsxm/ssqk/202202/t20220222_1926408.shtml",
        publishedAt: "2022-02-22",
      },
      time: "建议 16:30 – 18:30",
      kind: "常设目的地",
      tip: "¥15 为自选饮品预留，不是门票价格。临水区域受水位与封闭公告影响，出发前确认开放状态。",
    },
    art: {
      archived: true,
      kind: "暂停推荐",
      statusNote:
        "官方公告：2026 年 8 月 13 日起因维护闭馆，恢复时间另行公布。已从发现页下架。",
      source: {
        name: "湖北美术馆 · 临时闭馆公告",
        url: "https://wlt.hubei.gov.cn/hbmoa/zxdt/gx/202608/t20260807_5991139.shtml",
        publishedAt: "2026-08-07",
      },
    },
    music: {
      archived: true,
      kind: "旧版示例",
      statusNote:
        "旧版虚构演出示例，已停止推荐。保留此条仅供查看已有计划和记录。",
    },
    book: {
      archived: true,
      kind: "旧版示例",
      statusNote:
        "旧版未指定店铺的示例路线，已停止推荐。保留此条仅供查看已有计划和记录。",
    },
  };
  items.forEach((a) =>
    Object.assign(a, { checkedAt: "2026-09-17" }, metadata[a.id]),
  );
  items.push(
    {
      id: "wuhan-museum-night",
      title: "夜游武汉博物馆，和历史晚点告别",
      category: "艺术展览",
      place: "武汉博物馆 · 江汉区",
      price: 0,
      hours: 2,
      indoor: true,
      group: 6,
      tag: "官方夜游公告",
      image: "photo-1579783902614-a3fb3927b6a5",
      desc: "周末延时开放，把逛馆的时间留到傍晚。",
      tags: ["室内夜游", "免费参观"],
      time: "建议 18:00 – 20:00",
      transport: "武汉博物馆，青年路 373 号；按地图查询实时公共交通。",
      booking:
        "官方公告：周末延时至 20:30，20:00 停止入馆。假日安排另行通知，请先确认入馆要求。",
      route: "核实入馆安排 → 馆内参观 → 留意闭馆时间 → 结伴返程",
      tip: "2 小时为建议游览时长，不代表特定演出场次。可租用的导览服务等费用另计。",
      kind: "限时开放安排",
      startDate: "2026-09-05",
      endDate: "2026-12-31",
      weekdays: [0, 6],
      checkedAt: "2026-09-17",
      source: {
        name: "武汉市政府 · 周末延时开放公告",
        url: "https://www.wuhan.gov.cn/hdjl/rdhy/202609/t20260905_2843817.shtml",
        publishedAt: "2026-09-05",
      },
      extraSource: {
        name: "武汉市文旅局 · 免费参观说明",
        url: "https://wlj.wuhan.gov.cn/zfxxgk/fdzdgknr/jgjj/zsdw/202008/t20200827_1437246.shtml",
      },
    },
    {
      id: "optics-library",
      title: "去光谷图书馆，翻开一个慢周末",
      category: "艺术展览",
      place: "光谷文化中心 A 栋 · 光谷图书馆",
      price: 0,
      hours: 2,
      indoor: true,
      group: 4,
      tag: "真实阅读目的地",
      image: "photo-1507842217343-583bb7270b66",
      desc: "在公共阅读空间里，把周末留给一本书。",
      tags: ["室内阅读", "先核实预约"],
      time: "建议下午 · 以开馆时段为准",
      transport: "光谷文化中心 A 栋 2–4 层，毗邻地铁 11 号线光谷生物园站。",
      booking:
        "官方开馆公告说明试运营期间须在「光谷图书馆」微信公众号预约；请核实当前预约与营业政策。",
      route: "确认预约 → 选择阅览区 → 安静阅读 → 自行返程",
      tip: "此卡推荐场所，不承诺 7–8 月开馆展览仍在举办；饮食、交通及其他消费不计入免费阅读。",
      kind: "常设目的地",
      checkedAt: "2026-09-17",
      source: {
        name: "武汉市政府 · 光谷图书馆开馆公告",
        url: "https://www.wuhan.gov.cn/hdjl/rdhy/202607/t20260716_2821824.shtml",
        publishedAt: "2026-07-16",
      },
    },
    {
      id: "culture-2026",
      title: "长江文化艺术季，挑一场文化之约",
      category: "音乐演出",
      place: "武汉等城市 · 场地依具体活动",
      price: 0,
      hours: 2,
      indoor: false,
      group: 6,
      tag: "9.19 – 10.30",
      image: "photo-1470229722913-7c0e2dbbafd3",
      desc: "从舞台艺术到音乐与阅读，从官方活动菜单挑选你的周末。",
      tags: ["官方活动季", "先查具体场次"],
      time: "9 月 19 日 – 10 月 30 日；单场时间待查",
      transport:
        "这是跨场馆活动季线索；请在官方公告确认武汉具体场次后安排交通。",
      booking:
        "官方报道公布 11 项主体活动免费开放。具体领票方式、余票及地点需核实，本网站不提供实时票务。",
      route: "阅读官方发布 → 选择武汉场次 → 确认时间与领票 → 再安排出行",
      tip: "2 小时为预留时长，不是官方演出时长。活动含多种场景，未确认室内场次前不纳入雨天推荐。",
      kind: "活动季线索",
      startDate: "2026-09-19",
      endDate: "2026-10-30",
      checkedAt: "2026-09-17",
      source: {
        name: "武汉市商务局 · 长江文化艺术季发布",
        url: "https://sw.wuhan.gov.cn/xwdt/mtbd/202609/t20260909_2845392.shtml",
        publishedAt: "2026-09-09",
      },
    },
  );
  function available(a, date) {
    return (
      Boolean(a) &&
      !a.archived &&
      (!a.startDate || a.startDate <= date) &&
      (!a.endDate || a.endDate >= date) &&
      (!a.weekdays ||
        a.weekdays.includes(new Date(date + "T00:00:00Z").getUTCDay()))
    );
  }
  const api = { items, available };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else root.WeekendActivities = api;
})(typeof globalThis !== "undefined" ? globalThis : this);
